default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: best_library_development

test:
  <<: *default
  database: best_library_test

production:
  <<: *default
  database: best_library_production
